### ISSUE TITLE
Overall project discussion

### ISSUE THREAD

**Issue by satazor** [npms-io/npms-cli#1]
This thread serves as an open discussion to features, implementation details and misc stuff related to the CLI project.

I will keep the section below updated to what we have agreed upon.

*TODO*

**Comment by satazor** [comment]
I usually use the following modules to create CLI's:

- yargs for arguments processing and help usage
- update-notifier to notify CLI updates

Answering some of your points in https://github.com/npms-io/npms-api/issues/23#issuecomment-225459797

- linting rules: eslint + @satazor/eslint-config
- test runner: mocha
- assertion style: chai expect
- workflow: gitflow
- test structure: it really depends, but I usually do multiple `expects` in the same test
one assertion per test? multiple assertions per test?
- BDD

What are your thoughts?

**Comment by satazor** [comment]
Regarding creating a SDK layer, I don't really know.. It's one more piece of software to maintain and it will leak the abstraction. For instance, if the search response changes from a flat list to a nested list, you might want to return the new nested list instead of the flat list, e.g.:

```js
[{ name: 'jquery', version: '2.0.0', score: .., searchScore: ... }]  // flat list
[{ name: 'jquery', version: '2.0.0'}, score: ...,  searchScore: ...}] // nested list

Not doing so, will introduce discrepancies between the API and the SDK which will lead to confusion. Of course we could have proper versioning of the SDK but, without resorting to deprecation, we would need to maintain a lot of output various for the endpoints.

**Comment by dcrockwell** [comment]
I don't see the SDK as just "one more piece of software to maintain", as much as I see it being the driver for all client and server communication decisions.

In this way, the SDK changes are proposed first, then server and client changes proposed to match the SDK. This avoids any desyncing issues.

SDK can mean a lot of things, of course from a.) A full-blown Object Oriented Data Abstraction Layer, to z.) A simple communications abstraction for speaking with the server.

I am proposing the latter: a simple communications abstraction so that when you make changes to the server's request/response pattern, you can gracefully issue a patch and even eventually support legacy API versions for applications that integrate early.

**Comment by dcrockwell** [comment]
>  discrepancies between the API and the SDK

If you make the SDK the driver, then this cannot happen. Feature changes are proposed in the SDK first, then subsequent proposals are made for both the client and server to match the SDK.

**Comment by satazor** [comment]
@dcrockwell the thing is that not everyone will be using the SDK, especially the ones using other languages other than JS.

**Comment by satazor** [comment]
We will need to support every single change we make to the API, so that we do not break the SDK output. This will easily become very tedious :s

**Comment by dcrockwell** [comment]
I'm thinking in terms of the CLI.

Writing a CLI against raw REST requests will still require an object to centralize all of the calls, or it will have decentralized remote calls spaghetti'd throughout which is not ideal for workflow (especially if you're expecting changes).

If an object needs to be written to perform the REST requests anyways, doesn't it make sense to modularize that component so that it can be used as an easy form of integration for anybody using the primary language this search serves?

Otherwise, we just have an object we still have to maintain, but it's not useful outside of the CLI.

**Comment by satazor** [comment]
@dcrockwell I agree with you as long as we don't have to be backwards compatible in terms of the responses. This means that the SDK will be a simpler way to consume the API. Everytime the response is incompatible we need to bump the major version and deprecated the old one.

**Comment by satazor** [comment]
Created: https://github.com/npms-io/npms-api-client

**Comment by dcrockwell** [comment]
@satazor Sounds like a good initial plan.

Perhaps "npms-node", so that "npms-python" and more could be made in the future?

It may be a bit early to consider it, but looking into automating this layer with something like Swagger.io may be beneficial:
* it can be automatically generated the SDK in any language the project wants
* there's a single place to make changes for all languages generated, instead of maintaining many repos

**Comment by dcrockwell** [comment]
> linting rules: eslint + @satazor/eslint-config
> test runner: mocha
> assertion style: chai expect
> workflow: gitflow
> test structure: it really depends, but I usually do multiple expects in the same test
> BDD

Sounds good for everything except I suggest switching to a single assertion per test. It's only slightly more verbose and provides a standard for assertions. When there are more than one assertion in a single test, it can sometimes lead to ambiguous results on summaries, and extra work for the developer to figure out which assertion is failing.

**Comment by satazor** [comment]
> Perhaps "npms-node", so that "npms-python" and more could be made in the future?

> It may be a bit early to consider it, but looking into automating this layer with something like Swagger.io may be beneficial:

> - it can be automatically generated the SDK in any language the project wants
> - there's a single place to make changes for all languages generated, instead of maintaining many repos

I have never used swagger, did you? Do you think its good? My only concern is if we are overcomplicating things.

**Comment by satazor** [comment]
> Sounds good for everything except I suggest switching to a single assertion per test. It's only slightly more verbose and provides a standard for assertions. When there are more than one assertion in a single test, it can sometimes lead to ambiguous results on summaries, and extra work for the developer to figure out which assertion is failing.

SGTM, the tests for the CLI will be simple. Regarding coverage, I use istanbul and coveralls.

**Comment by dcrockwell** [comment]
I have not used Swagger or anything like it, really. I've just heard some rumors about it being good for this sort of thing.

I'm 100% with you on taking the Amish approach to technological adoption: if it makes things convenient at the expense of overly complicating another aspect of life, it should be rejected.

If automating this layer is more trouble than it's worth, it should be disregarded, but perhaps it's worth an hour of research to know that for sure.

**Comment by satazor** [comment]
> If automating this layer is more trouble than it's worth, it should be disregarded, but perhaps it's worth an hour of research to know that for sure.

Alright, will you try it out and report back?

**Comment by dcrockwell** [comment]
> SGTM, the tests for the CLI will be simple. Regarding coverage, I use istanbul and coveralls.

Perfect. We have an identical testing stack.

I think 100% coverage is the only coverage worth going for, unless you can identify with certainty that only specific key parts warrant testing, and the other specific parts do not.

Plus, "86.2%" coverage doesn't have much meaning to anybody.

**Comment by dcrockwell** [comment]
That said, there are certain aspects of testing a CLI which call into question what constitutes 100% coverage, as istanbul cannot instrument the CLI code from what I can see.

**Comment by satazor** [comment]
> That said, there are certain aspects of testing a CLI which call into question what constitutes 100% coverage, as istanbul cannot instrument the CLI code from what I can see.

You are right, but if the CLI bin is simply enough to call functions based on the commands, perhaps it doesn't need to be tested. If you still need to test it, I think there was a module that does what you want, and I think that AVA uses it.

**Comment by dcrockwell** [comment]
Yeah, this CLI will be simpler than others. It won't require much more than some basic integration testing for: help(-h,--help), version (-V,--version), that errors passed from the library are thrown, and that each function has basic coverage against errors.

**Comment by rhettl** [comment]
Any thoughts on commander over yargs?
A good argument in favor of the SDK is that it's easier to unit test the SDK then E2E test the CLI with some unit tests here and there.

**Comment by satazor** [comment]
I have had so many troubles with commander in the past that I've totally gave up..I can't remember them exactly but they were so frustrating..

**Comment by dcrockwell** [comment]
> Any thoughts on commander over yargs?

commander has some advantages when creating complex "git-like" interfaces, but ends up being high-calorie sugar for super-simple CLIs like I presume this one to be.

(@satazor perhaps defining what the CLI features will be can be the next step.)

> it's easier to unit test the SDK then E2E test the CLI with some unit tests here and there.

In my experience, CLI testing is black-boxed, so the choice of CLI library is inconsequential to testing.

https://github.com/tj/commander.js/issues/438

**Comment by satazor** [comment]
@dcrockwell I see two essential features for launch:

- search of modules
- get collected, evaluation and score info of a given module

We don't need to do any offline support for now.

**Comment by dcrockwell** [comment]
@satazor Excellent. Let's begin nailing down exactly how we envision it looking from the CLI. Does this look about right to you as a first stake in the ground?

**Basic Search:**

``` shell
$ npms search mrt

Searching {search url here}..
1 package found!

mrt@0.2.0
```

**Partial Search:**

``` shell
$ npms search mr

Searching {search url here}..
3 packages found!

mrt@0.2.0
mrdo@2.1.0
mre@0.0.1
```

**JSON output:**

Actually this section poses an issue. What format will the JSON take, and what's best for future growth?

I personally think this may be a job for [http://jsonapi.org/](http://jsonapi.org/). It has built-in considerations for relationships, meta-data, and pagination.

Any standard like it would work, but it's the only one I know of so far.

``` shell
$ npms search mrt --json
{
    ???
}
```

**Opt-Out:**

Not sure how this would be handled.

**Comment by satazor** [comment]
Whats the difference between basic and partial search?


```$ npms search jquery

$ npms search mrt

Searching {search url here}..
667 packages found!

jquery@2.0.0 <score> <repo>
...

$npms info jquery

{
   collected: { metadata: {}, github: {}, ... },
   evaluation: {},
   score: {}
}
```

Regarding the --json option: when you are rendering a template, you specify an object which contains the data to be interpolated. The --json option spits that data directly.. thats how I envision it.

**Comment by dcrockwell** [comment]
> Whats the difference between basic and partial search?

Nothing. Just two examples to show full and partial searching with the same interface without the need for wildcards.

> The --json option spits that data directly

I think there's a need for both a human-readable and machine-readable interface, and that JSON does not fit both use cases well.

So, I would prefer something similar to this:

``` shell
$ npms info jquery
jQuery@3.0.0

Score: 2.4
Evaluation:
    coverage: 100%
    lines: 268
    size: 10kb
```

```
$ npms info jquery --json
{
   collected: { metadata: {}, github: {}, ... },
   evaluation: {},
   score: {}
}
```

**Comment by dcrockwell** [comment]
Perhaps the concept of `reporters` should be built in from the get-go?

**Comment by satazor** [comment]
@dcrockwell yes, that was an example.. we could use something like https://www.npmjs.com/package/print-object or https://www.npmjs.com/package/purdy for the human readable output of `npms info`

**Comment by satazor** [comment]
> Perhaps the concept of reporters should be built in from the get-go?

@dcrockwell as long as it is simple.. I don't want to complicate things too much

**Comment by dcrockwell** [comment]
@satazor print-object looks good. Purdy has nice colors. If their powers could combine...

> as long as it is simple.. I don't want to complicate things too much

We've already established that we're a techno-amish village :D

**Comment by satazor** [comment]
Here's all the info that we have for `npms info cross-spawn` for reference:

```json
{
   "startedAt": "2016-06-10T21:12:41.268Z",
   "finishedAt": "2016-06-10T21:12:45.502Z",
   "collected": {
       "metadata": {
           "name": "cross-spawn",
           "version": "4.0.0",
           "description": "Cross platform child_process#spawn and child_process#spawnSync",
           "keywords": [
               "spawn",
               "spawnSync",
               "windows",
               "cross",
               "platform",
               "path",
               "ext",
               "path-ext",
               "path_ext",
               "shebang",
               "hashbang",
               "cmd",
               "execute"
           ],
           "date": "2016-05-26T20:50:45.929Z",
           "publisher": {
               "username": "satazor",
               "email": "andremiguelcruz@msn.com"
           },
           "maintainers": [
               {
                   "username": "satazor",
                   "email": "andremiguelcruz@msn.com"
               }
           ],
           "author": {
               "name": "IndigoUnited",
               "email": "hello@indigounited.com",
               "url": "http://indigounited.com"
           },
           "repository": {
               "type": "git",
               "url": "git://github.com/IndigoUnited/node-cross-spawn.git"
           },
           "links": {
               "npm": "https://www.npmjs.com/package/cross-spawn",
               "homepage": "https://github.com/IndigoUnited/node-cross-spawn#readme",
               "repository": "https://github.com/IndigoUnited/node-cross-spawn",
               "bugs": "https://github.com/IndigoUnited/node-cross-spawn/issues/"
           },
           "license": "MIT",
           "dependencies": {
               "lru-cache": "^4.0.1",
               "which": "^1.2.9"
           },
           "devDependencies": {
               "@satazor/eslint-config": "^2.3.0",
               "eslint": "^2.10.2",
               "expect.js": "^0.3.0",
               "glob": "^7.0.0",
               "mkdirp": "^0.5.1",
               "mocha": "^2.2.5",
               "rimraf": "^2.5.0"
           },
           "releasesFrequency": [
               {
                   "from": "2016-05-17T00:00:00.000Z",
                   "to": "2016-06-16T00:00:00.000Z",
                   "count": 4
               },
               {
                   "from": "2016-03-18T00:00:00.000Z",
                   "to": "2016-06-16T00:00:00.000Z",
                   "count": 7
               },
               {
                   "from": "2015-12-19T00:00:00.000Z",
                   "to": "2016-06-16T00:00:00.000Z",
                   "count": 12
               },
               {
                   "from": "2015-06-17T00:00:00.000Z",
                   "to": "2016-06-16T00:00:00.000Z",
                   "count": 20
               },
               {
                   "from": "2014-06-17T00:00:00.000Z",
                   "to": "2016-06-16T00:00:00.000Z",
                   "count": 42
               }
           ],
           "hasTestScript": true,
           "readme": "bla bla.."
       },
       "npm": {
           "downloads": [
               {
                   "from": "2016-06-09T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 54342
               },
               {
                   "from": "2016-06-03T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 315468
               },
               {
                   "from": "2016-05-11T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 1201910
               },
               {
                   "from": "2016-03-12T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 4573329
               },
               {
                   "from": "2015-12-13T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 9094614
               },
               {
                   "from": "2015-06-11T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 15751560
               }
           ],
           "dependentsCount": 185,
           "starsCount": 11
       },
       "github": {
           "starsCount": 81,
           "forksCount": 13,
           "subscribersCount": 12,
           "issues": {
               "count": 35,
               "openCount": 1,
               "distribution": {
                   "3600": 9,
                   "10800": 3,
                   "32400": 3,
                   "97200": 6,
                   "291600": 4,
                   "874800": 2,
                   "2624400": 5,
                   "7873200": 1,
                   "23619600": 2,
                   "70858800": 0,
                   "212576400": 0
               },
               "isDisabled": false
           },
           "contributors": [
               {
                   "username": "satazor",
                   "commitsCount": 120
               },
               {
                   "username": "BigstickCarpet",
                   "commitsCount": 4
               },
               {
                   "username": "timdp",
                   "commitsCount": 2
               },
               {
                   "username": "greenkeeperio-bot",
                   "commitsCount": 1
               },
               {
                   "username": "typicode",
                   "commitsCount": 1
               },
               {
                   "username": "ForbesLindesay",
                   "commitsCount": 1
               },
               {
                   "username": "kevva",
                   "commitsCount": 1
               },
               {
                   "username": "knpwrs",
                   "commitsCount": 1
               }
           ],
           "commits": [
               {
                   "from": "2016-06-03T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 0
               },
               {
                   "from": "2016-05-11T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 11
               },
               {
                   "from": "2016-03-12T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 19
               },
               {
                   "from": "2015-12-13T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 38
               },
               {
                   "from": "2015-06-11T00:00:00.000Z",
                   "to": "2016-06-10T00:00:00.000Z",
                   "count": 71
               }
           ],
           "statuses": [
               {
                   "context": "continuous-integration/appveyor/branch",
                   "state": "success"
               },
               {
                   "context": "continuous-integration/travis-ci/push",
                   "state": "success"
               }
           ]
       },
       "source": {
           "files": {
               "readmeSize": 2759,
               "testsSize": 23602,
               "hasNpmIgnore": true,
               "hasShrinkwrap": false
           },
           "repositorySize": 39216,
           "linters": {
               "general": [
                   "editorconfig"
               ],
               "js": [
                   "eslint"
               ]
           },
           "badges": [
               {
                   "urls": {
                       "original": "http://img.shields.io/npm/dm/cross-spawn.svg",
                       "shields": "https://img.shields.io/npm/dm/cross-spawn.svg",
                       "content": "https://img.shields.io/npm/dm/cross-spawn.json"
                   },
                   "info": {
                       "service": "npm",
                       "type": "downloads",
                       "modifiers": {
                           "type": "dm"
                       }
                   }
               },
               {
                   "urls": {
                       "original": "http://img.shields.io/npm/v/cross-spawn.svg",
                       "shields": "https://img.shields.io/npm/v/cross-spawn.svg",
                       "content": "https://img.shields.io/npm/v/cross-spawn.json"
                   },
                   "info": {
                       "service": "npm",
                       "type": "version",
                       "modifiers": {
                           "type": "v"
                       }
                   }
               },
               {
                   "urls": {
                       "original": "http://img.shields.io/travis/IndigoUnited/node-cross-spawn/master.svg",
                       "service": "https://api.travis-ci.org/IndigoUnited/node-cross-spawn.svg?branch=master",
                       "shields": "https://img.shields.io/travis/IndigoUnited/node-cross-spawn/master.svg",
                       "content": "https://img.shields.io/travis/IndigoUnited/node-cross-spawn/master.json"
                   },
                   "info": {
                       "service": "travis",
                       "type": "build",
                       "modifiers": {
                           "branch": "master"
                       }
                   }
               },
               {
                   "urls": {
                       "original": "https://img.shields.io/david/IndigoUnited/node-cross-spawn.svg",
                       "service": "https://david-dm.org/IndigoUnited/node-cross-spawn.svg",
                       "shields": "https://img.shields.io/david/IndigoUnited/node-cross-spawn.svg",
                       "content": "https://img.shields.io/david/IndigoUnited/node-cross-spawn.json"
                   },
                   "info": {
                       "service": "david",
                       "type": "dependencies",
                       "modifiers": {
                           "statusType": "normal"
                       }
                   }
               },
               {
                   "urls": {
                       "original": "https://img.shields.io/david/dev/IndigoUnited/node-cross-spawn.svg",
                       "service": "https://david-dm.org/IndigoUnited/node-cross-spawn/dev-status.svg",
                       "shields": "https://img.shields.io/david/dev/IndigoUnited/node-cross-spawn.svg",
                       "content": "https://img.shields.io/david/dev/IndigoUnited/node-cross-spawn.json"
                   },
                   "info": {
                       "service": "david",
                       "type": "dependencies",
                       "modifiers": {
                           "statusType": "dev"
                       }
                   }
               }
           ]
       }
   },
   "evaluation": {
       "quality": {
           "carefulness": 1,
           "tests": 0.85,
           "dependenciesHealth": 1,
           "branding": 0.6
       },
       "popularity": {
           "communityInterest": 125,
           "downloadsCount": 1524443,
           "downloadsAcceleration": 1069.845547945204,
           "dependentsCount": 185
       },
       "maintenance": {
           "recentCommits": 1,
           "commitsFrequency": 0.9573424657534246,
           "openIssues": 1,
           "issuesDistribution": 0.982274025974026
       }
   }
}
```

**Comment by satazor** [comment]
> print-object looks good. Purdy has nice colors. If their powers could combine...

The good news is that we can now use npms to search for a good module https://npms.io/search?term=print+object

**Comment by rhettl** [comment]
> print-object looks good. Purdy has nice colors. If their powers could combine...

I spent the last hour or so trying to find a way to make either be easily human readable, have purdy colors, **and** be able to pipe to a `JSON.parse()`. Sadly, no 😢 

In my last CLI, I added [this module][1]. Nothing special, just utilizing `chalk`, but it was fast and painless. It can always be re-implemented with the perfect pretty-print operator when it is found.

[1]: https://github.com/uci-soe/uci-directory-search/blob/master/lib/prettyFormat.js

**Comment by dcrockwell** [comment]
@satazor Have you considered JSON-API? There are utilities that integrate with it automatically.

**Comment by satazor** [comment]
Yes, it looks more suitable to HTTP API's because of the `links` and stuff.. I don't think we need it..

**Comment by flesch** [comment]
Hey there! I put together an `npms` CLI – it doesn't meet all the requirements above (I wrote most of it before finding this thread), but thought you'd like to see it:

<https://github.com/flesch/npms-cli>

I did push it to npm, but I'm not intending to step on any toes, so I'm happy to change the name or even transfer ownership to your org.

**Comment by satazor** [comment]
@flesch That looks good!

One minor thing I would change: since we expect to have more commands, such as `info`, the `bin/npms.js` will become very complex. Would you mind refactoring the `search` code into lib/search.js?

Could you also add `eslint` and `editorconfig` to the project?

@dcrockwell what do you think of @flesch work?

**Comment by mikeerickson** [comment]
@flesch @satazor I am glad I stumbled upon this thread before the weekend hit as I was planning on creating a CLI as well.  Now I can work on something else :-)

**Comment by flesch** [comment]
@satazor Awesome - I will definitely make those changes! @mikeerickson is going to add some tests too (<https://github.com/flesch/npms-cli/issues/3>).

**Comment by dcrockwell** [comment]
Hey guys, I've been moving to another city for days.

I think @flesch's work is simple enough, but we should stick to our guns and do it 100% test-driven from the beginning with continuous integration. It could be good to have *something* now, but that will result in a lot of people needing to rework their integrations.

I also think that npms-cli ought to be the official package name, so @flesch ought to transfer ownership to `npms-io` before any more versioned publishes are made (which will have to be unpublished, and can't be re-used).

Seeing as we're in a pre-alpha stage now, we should start on version `0.0.0` until we have an alpha to publish as `0.0.x`. From there, the first beta release would be `0.1.0`, and then the official first gold release be `1.0.1` (as `1.0.0` can not be used again).

Testing first is a mandatory requirement for my participation on a project.

**Comment by dcrockwell** [comment]
Since it seems there are more than a few of us who want this thing and are willing to do some work to get the ball rolling, I'd like to propose the following next steps:

1. Stub an initial spec. No working test code. Just behavior stubs.
2. Approve the stubs.

After the stubs are approved, we can break it up by feature and delegate the work out to multiple devs.

We can use `git flow` features to make sure we don't step on each other's feet.

**Comment by dcrockwell** [comment]
I also think that if @flesch is cool with it, we could copy and paste his code into our features so that they make our tests pass with a little modification. This way his work is still utilized.

**Comment by mikeerickson** [comment]
@dcrockwell Sounds like you have it all planned, have fun!

**Comment by dcrockwell** [comment]
It's really all up to @satazor to call the shots. I'm only offering suggestions to try and keep the original project requirements met.

**Comment by mikeerickson** [comment]
@dcrockwell You requirements are your requirements, I am not going to object.  I have plenty of projects to work on.  If this project is open for contributions, I will reevaluate at that time.   There was progress made this well and I (and @flesch) were stepping in to try and help.

But you have other plans, so I will step back

**Comment by satazor** [comment]
This is a community project, so lets join forces and work this out together. @flesch's work is a good start but I must agree that some goals were left behind:

- Use update-notifier
- Support JSON output with --json
- Create an SDK to consume the API, and use it in the npms-cli project
- eslint + editorconfig
- Tests

I want this project to be easy to maintain and to modify, so tests are a must. I would really love to have all of you work on this together, so please do not fight each other. I'm sure we can setup some common ground.

Having that said, I suggest that we follow our initial goals and use @flesch work in the process. 

@dcrockwell When are you able to use some of your time on planning the stubs?

**Comment by dcrockwell** [comment]
@satazor I can make the initial stubs tonight and submit them to this repo as a PR. Then the PR could be used as discussion for accepting/rejecting/modifying the proposed stubs

**Comment by dcrockwell** [comment]
@satazor I can't fork the repo until at least a README.md is committed, but I can still work on the stubs.

**Comment by satazor** [comment]
@dcrockwell done.

**Comment by dcrockwell** [comment]
Going to need to finish this up tomorrow and the next day.

**Comment by flesch** [comment]
I've added @satazor and @dcrockwell to the owners of <https://www.npmjs.com/package/npms-cli> so you guys can publish when you're ready. I've also deprecated v1.0.0.

Do you mind if I publish one more release to work with the new API format? The latest response format broke my version, leaving a few users hanging.

**Comment by dcrockwell** [comment]
@flesch I'm just a contributor to the project and not an owner. @satazor should be the sole owner.

That said, in my *personal opinion* I think if you publish another version, it should probably be `0.0.1` to signify it as an alpha.

**Comment by satazor** [comment]
@flesch go ahead and push 1.0.1

**Comment by mikeerickson** [comment]
@satazor @flesch I will be submitting PR for the fix Saturday, I will post here when completed as well

**Comment by mikeerickson** [comment]
@satazor @flesch All done here https://github.com/flesch/npms-cli/pull/6  Updated version to 1.0.1 as outlined above.

**Comment by flesch** [comment]
I just pushed v1.0.1 to npm - it supports the new API format (thanks @mikeerickson!). I also did refactor the code to move the "search" command into its own file. It's a start towards some of the requirements above, but let me know how I can continue to help!

**Comment by satazor** [comment]
Since @dcrockwell appears to be overwhelmed with work I propose that we embrace @flesch work into the official repository. If you agree @flesch I will be giving you access to the cli repository so that you can push your work into it.

- [ ] Remove warning notice from the README
- [ ] Add eslint config to the repository, preferably using the same eslint config from other npms repositories
- [ ] Add devDependencies badge to README
- [ ] Create an issue in the repository to add tests
- [ ] Update LICENSE, see: https://github.com/npms-io/npms-www/commit/66cf251803c89c4eb45ecd8cf0cd2591cee9fbc2

After migrating to the npms repository can you make the above changes @flesch?

**Comment by dcrockwell** [comment]
@satazor Sounds like a good plan. I'm very behind on a few repos and thought I would be done by now. Apologies for affecting your release schedule.

**Comment by flesch** [comment]
:+1: I'll try to make these changes soon!

**Comment by flesch** [comment]
@satazor I just pushed a couple of the quicker changes. I'll work on getting linting in as soon as I can.

**Comment by satazor** [comment]
@flesch Thank you very much for your hard work <3

**Comment by satazor** [comment]
I'm going to close this issue since the discussion is pretty much done now. Thanks for all thr contributions you guys made.
