### ISSUE TITLE
Provide ability to open to npms.io or npmjs.com (in addition to github)

### ISSUE THREAD

**Issue by mikeerickson** [npms-io/npms-cli#10]
Expand `open` sub-command to open link in `npms.io` or `npmjs.com`

Example:

```
$ npms open npms-cli --npms
$ npms open npms-cli --npmjs
$ npms open npms-cli --github (default)
```

If flag not supplied default will be used (which is github)

**Comment by satazor** [comment]
Do you feel this is really necessary? E.g.: the website doesn't provide that and no-one asked for that feature yet.

**Comment by mikeerickson** [comment]
Well, in my case I prefer to open the package in npmjs.org (but that is just personal preference)  In most cases, I don't go to github project first.   No one has asked until now :-)

**Comment by satazor** [comment]
Alright, this is fairly easy to add. Are you willing to add a PR?

**Comment by mikeerickson** [comment]
@satazor yes, I will add it and submit PR

**Comment by satazor** [comment]
@mikeerickson Feel free to add this on top of master, which has tests.

**Comment by mikeerickson** [comment]
@sataroz ok, will do

**Comment by mikeerickson** [comment]
@satazor Learned a few things about testing with your updates, thx 👍 

Now to get to work on the other flags outlined above

**Comment by satazor** [comment]
@mikeerickson great :) with a bit of imagination we can improve things!

**Comment by mikeerickson** [comment]
@satazor all done -- PR https://github.com/npms-io/npms-cli/pull/17
