### ISSUE TITLE
Provide ability to search on multiple items

### ISSUE THREAD

**Issue by mikeerickson** [npms-io/npms-cli#11]
I don't see any method for performing searches on multiple parameters?

```
$ npms search [npms-cli,gulp]
$ npms search npms-cli gulp
```

Thinking this would be something better served in the `search` API code (not the CLI code) so that the user would be able to perform same type of search from website

If you are OK with this change (even at the CLI level) I can go ahead and knock it out

**Comment by flesch** [comment]
What do you mean? Searching with multiple keywords is already supported in both the API and the CLI.

`npms search react redux` will create a request like this: https://api.npms.io/search?term=react%20redux

**Comment by mikeerickson** [comment]
@flesh try this

```
$ npms search cd-messenger gulp-messenger
```

On this end, it only returns one result, whereas it should return two.

**Comment by flesch** [comment]
I think what you're looking for is here: https://github.com/npms-io/npms-api/issues/29#issuecomment-230165366

As far as the CLI is concerned it should work the same as the web interface.

**Comment by mikeerickson** [comment]
Well then, I never saw this response :)

Thx for link

**Comment by mikeerickson** [comment]
@flesch Well, I looked at this and multiple terms are NOT supported as I am trying to use them.  As this ticket indicates, these terms are used as AND comparisons, not OR comparison.  

Therefore, this request still has merit and is NOT currently supported so far as I understand.

@satazor What are you thoughts on this item?  Is this something you would be willing to add to the API?  Bottom line, what I am looking for is OR support

Pseudo code, actual syntax may vary

```
$ npms search gulp-messenger OR cd-messenger 
```

**Comment by satazor** [comment]
The multiple terms work as AND and not OR in the API as this is the expected default behavior, e.g.: web framework should yield results for both terms imho.

**Comment by mikeerickson** [comment]
@satazor do you want me to add it and submit PR, or are you going to take it?

**Comment by satazor** [comment]
At the moment I don't have much time so it could take longer to add that feature. Still it's pretty easy to add that, we just need to agree on the query parameter name and values, e.g.: ?operator=and/or

**Comment by mikeerickson** [comment]
--operator approach looks good to me 

I will add it to the todo list and will allocate time to get it done in coming days/weeks
