### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by flesch** [npms-io/npms-cli#2]
There are currently no tests and `npm test` fails.  Perhaps @mikeerickson wants to lend a hand?

- [x] Add tests using mocha + chai BDD
- [x] Integrate istanbul + coveralls
- [x] Add travis badge to README
- [x] Add coveralls badge to README
- [x] Add how to run tests in the README

**Comment by satazor** [comment]
I've add a list to make sure we don't forget integrations.

**Comment by mikeerickson** [comment]
@flesch @satazor If you all still want me to work on tests, I am willing to offer my assistance.

**Comment by satazor** [comment]
We absolutely need some help!

**Comment by rickycodes** [comment]
1. What versions of node to add to travis build? (this can be added to #8)
2. What test harness should be used/etc? (Tape, mocha, etc.)

I can also lend a hand/get started with this if you'd like 😉

**Comment by satazor** [comment]
1. Node 4 and 6
2. Mocha + chai (bdd) + istanbul

**Comment by rickycodes** [comment]
@satazor

wondering if I can get added as contributor so I can start checking some of these things off? (including the now completed item: "Add travis badge to README")

feel free to assign this to me as well 😄

**Comment by mikeerickson** [comment]
I have created a dozen tests or so, will submit PR later today when I return home (don't have code w/ me at work)

**Comment by mikeerickson** [comment]
@rickycodes hold off on addressing tests until after my PR is merged as it has all the tooling for tests already completed

**Comment by rickycodes** [comment]
@mikeerickson ah, ok sounds good! :)

**Comment by mikeerickson** [comment]
@rickycodes FYI, I will be posting all the testing stuff as soon as next version of cli is done.
@flesch is adding some new shortcuts to CLI, just waiting for him to finish that up.

**Comment by flesch** [comment]
Don't wait for me – might close #13 soon as I can't get it to work.

**Comment by mikeerickson** [comment]
@flesch OK, I will post what I have tomorrow and then updates the tests accordingly when you art done.

**Comment by satazor** [comment]
@mikeerickson any news?

**Comment by mikeerickson** [comment]
@satazor sorry, been dealing with some family issues (nephew in serious accident). I will post later today

**Comment by mikeerickson** [comment]
@satazor OK, I have created a PR which contains all the CLI tests at the moment.  I will update tests accordingly to address any new features, etc.
