### ISSUE TITLE
Change options from camelcase to slashes.

### ISSUE THREAD

**Issue by satazor** [npms-io/npms-cli#6]
As @sindresorhus suggested, do  you agree @flesch?

**Comment by satazor** [comment]
One thing in favor of camelCase is that it goes inline with the API, since its query string arguments are also camelCase as well as the response.

**Comment by satazor** [comment]
PR: #7

**Comment by flesch** [comment]
I like the change.

**Comment by flesch** [comment]
Or we could drop what's after the dash now. `--popularity-weight` could be just `--popularity`...

**Comment by satazor** [comment]
I would keep the *-weight since it matches the API. Actually changing to dashes will make it backwards compatible since `--scoreEffect` would still work (just tested it out).

Going to merge #7 if it's ok?

**Comment by flesch** [comment]
Sounds good! That's makes it easier that it's backwards compatible.

**Comment by satazor** [comment]
Done!
